#!/bin/bash
#SBATCH -J comparealgs     # Job name
#SBATCH -o comparealgs_%j.txt # Name of stdout output file
#SBATCH -e comparealgs_%j.txt # Name of stderr error file
#SBATCH -p normal          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes
#SBATCH -n 1               # Total # of mpi tasks
#SBATCH -t 00:30:00        # Run time (hh:mm:ss)
#SBATCH -A EE-382C-EE-361C-Mult # Allocation name
#SBATCH --mail-user=user@email.com # Replace by your email
#SBATCH --mail-type=all    # Send email at begin and end of job

# Job to run
echo "Date: $(date)"
echo "Working directory: $(pwd)"
echo "Module list:"
module list
echo "Running job..."
~/go/bin/comparealgs input_n_1K.txt output_n_1K.txt
echo "Done"
